### ISSUE TITLE
how to do numpy in mpi

### ISSUE THREAD

**Issue by eselige** [cloudmesh/cloudmesh-mpi#27]
https://github.com/cloudmesh/cloudmesh-mpi/blob/main/doc/chapters/report-mpi.md#using-numpy-with-mpi4py

**Comment by shekinah-lungu** [comment]
HOW TO DO NUMPY IN MPI
Download Numpy with pip install Numpy in a terminal
Import numpy as np to use numpy in the program
Advantages of numpy over lists
Numpy stores memory contiguously
Uses a smaller number of bytes
You can multiply arrays by index
It’s faster
You can store different data types including images
Contains random number generators

Numpy syntax
Making one dimensional arrays
To define an array type: np.nameofarray([1,2,3])
To get the dimension of the array: nameofarray.ndim
To get the shape of the array(the number of rows and columns): nameofarray.shape
To get the type of the array: nameofarray.dtype
To get the number of bytes: nameofarray.itemsize
To get the number of elements in the array: nameofarray.size
To get the total size: nameofarray.size * nameofarray.itemsize

**Comment by laszewsk** [comment]
Please remember we may have lots of numpy tutorials in the python book. The emphasize here is how to use numpy within MPI not to explain every feature of numpy

**Comment by flealc** [comment]
Added the section briefly explaining what NumPy is before it is used in mpi4py communication examples. Pointed to Python for Cloud Computing book for reference on installation and further use of NumPy
See in document here: https://github.com/cloudmesh/cloudmesh-mpi/blob/main/doc/chapters/report-mpi.md#using-numpy-with-mpi4py
