### ISSUE TITLE
 Document mpi4py tutorial - Collective communication examples

### ISSUE THREAD

**Issue by flealc** [cloudmesh/cloudmesh-mpi#5]
- [x] add images
- [x] Broadcasting a Python dictionary
- [x] Scattering Python objects
- [x] Gathering Python objects
- [x] Broadcasting a NumPy array
- [x] Scattering NumPy arrays
- [x] Gathering NumPy arrays
- [x] Allgather with NumPy arrays

**Comment by laszewsk** [comment]
please can you check if all are included properly in mpi.md

**Comment by flealc** [comment]
Will do for sure before the meeting

**Comment by laszewsk** [comment]
i just pushed newest pdf and adde link channel in slack s its easier to find

**Comment by laszewsk** [comment]
has this been completed?
